
alter table item_catalog add column if not exists modifiers jsonb;

drop function if exists logistics_list_pending_tag_requests();
create or replace function logistics_list_pending_tag_requests()
returns table(
  id uuid,
  player_display_name text,
  character_name text,
  item_name text,
  quantity integer,
  event_slug text,
  created_at timestamptz,
  code text,
  modifier_type text,
  use_count integer,
  modifiers jsonb
) language plpgsql stable security definer
set search_path = public
as $$
begin
  if not fa_is_logistics_or_admin() then
    raise exception 'Staff only';
  end if;

  return query
    select
      r.id,
      coalesce(p.display_name, u.raw_user_meta_data ->> 'display_name', u.email)::text,
      c.name,
      r.item_name,
      r.quantity,
      r.event_slug,
      r.created_at,
      ic.code,
      coalesce(ic.modifier_type, 'none'),
      ic.use_count,
      ic.modifiers
    from character_tag_requests r
    join characters c on c.id = r.character_id
    join auth.users u on u.id = r.player_id
    left join profiles p on p.id = r.player_id
    left join item_catalog ic on lower(ic.item_name) = lower(r.item_name)
    where r.status = 'pending'
    order by coalesce(p.display_name, u.raw_user_meta_data ->> 'display_name', u.email), c.name, r.item_name;
end;
$$;

revoke all on function logistics_list_pending_tag_requests() from public, anon;
grant execute on function logistics_list_pending_tag_requests() to authenticated;

insert into item_catalog (item_name, modifiers) values
  ('1 Loc (1.25 AP) Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.25 AP) Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.25 AP) Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) Kereste Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Chain Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Gambeson Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Hardened Leather Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Leather Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Mithril Chain Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Mithril Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Mithril Scale Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Plate Kereste Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Scale Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Scale Kereste Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Silver Chain Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Silver Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Silver Scale Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.5 AP) MC Studded Leather Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.875 AP) MC Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.875 AP) MC Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('1 Loc (1.875 AP) MC Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 1}]'::jsonb),
  ('10 Loc (12.5 AP) Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 12}]'::jsonb),
  ('10 Loc (12.5 AP) Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 12}]'::jsonb),
  ('10 Loc (12.5 AP) Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 12}]'::jsonb),
  ('10 Loc (15 AP) MC Chain Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Gambeson Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Hardened Leather Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Leather Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Mithril Chain Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Mithril Plate Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Mithril Scale Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Plate Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Plate Kereste Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Scale Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Scale Kereste Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Silver Chain Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Silver Plate Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Silver Scale Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (15 AP) MC Studded Leather Armour', '[{"label": "Perm AP Dmg", "count": 14}]'::jsonb),
  ('10 Loc (18.75 AP) MC Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 18}]'::jsonb),
  ('10 Loc (18.75 AP) MC Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 18}]'::jsonb),
  ('10 Loc (18.75 AP) MC Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 18}]'::jsonb),
  ('10 Loc/AP Chain Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Gambeson Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Hardened Leather Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Kereste Plate Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Leather Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Mithril Chain Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Mithril Plate Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Mithril Scale Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Plate Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Scale Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Scale Kereste Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Silver Chain Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Silver Plate Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Silver Scale Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('10 Loc/AP Studded Leather Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('1h Bolts (10) - Adamantine', '[{"label": "Used", "count": 10}]'::jsonb),
  ('1h Bolts (10) - Kereste', '[{"label": "Used", "count": 10}]'::jsonb),
  ('1h Bolts (10) - Mithril', '[{"label": "Used", "count": 10}]'::jsonb),
  ('1h Bolts (10) - Silver', '[{"label": "Used", "count": 10}]'::jsonb),
  ('1h Crossbow - Kereste and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Crossbow - MC Kereste and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Crossbow - MC and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Crossbow and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('1h Spear - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('1h Spear - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('1h Spear - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Bolts (10) - Adamantine', '[{"label": "Used", "count": 10}]'::jsonb),
  ('2h Bolts (10) - Kereste', '[{"label": "Used", "count": 10}]'::jsonb),
  ('2h Bolts (10) - Mithril', '[{"label": "Used", "count": 10}]'::jsonb),
  ('2h Bolts (10) - Silver', '[{"label": "Used", "count": 10}]'::jsonb),
  ('2h Crossbow - Kereste and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Crossbow - MC Kereste and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Crossbow - MC and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Crossbow and Bolts', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('2h Spear - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('2h Spear - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('2h Spear - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('5 Loc (6.25 AP) Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 6}]'::jsonb),
  ('5 Loc (6.25 AP) Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 6}]'::jsonb),
  ('5 Loc (6.25 AP) Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 6}]'::jsonb),
  ('5 Loc (7.5 AP) MC Chain Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Gambeson Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Hardened Leather Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Leather Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Mithril Chain Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Mithril Plate Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Mithril Scale Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Plate Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Plate Kereste Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Scale Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Scale Kereste Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Silver Chain Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Silver Plate Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Silver Scale Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (7.5 AP) MC Studded Leather Armour', '[{"label": "Perm AP Dmg", "count": 7}]'::jsonb),
  ('5 Loc (9.375 AP) MC Adamantine Chain Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('5 Loc (9.375 AP) MC Adamantine Plate Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('5 Loc (9.375 AP) MC Adamantine Scale Armour', '[{"label": "Perm AP Dmg", "count": 9}]'::jsonb),
  ('5 Loc/AP Chain Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Gambeson Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Hardened Leather Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Leather Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Mithril Chain Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Mithril Plate Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Mithril Scale Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Plate Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Plate Kereste Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Scale Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Scale Kereste Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Silver Chain Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Silver Plate Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Silver Scale Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('5 Loc/AP Studded Leather Armour', '[{"label": "Perm AP Dmg", "count": 4}]'::jsonb),
  ('Acid (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Adrenal Rush (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Alcohol - Churning Waters Wine (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Deepwood Wine (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Eldersire Port (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Harodom Brandy (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Magedom Scotch (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Michian Beer (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Mythostar Vermouth (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Skrulmiter Gin (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Sorr Bukra Moonshine (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Alcohol - Splishenfellow "Drink" (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Antidote (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arcane Death (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arcane Ink (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arrows (10) - Adamantine', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arrows (10) - Kereste', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arrows (10) - Mithril', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Arrows (10) - Silver', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Awakener (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Bandage - MC', '[{"label": "Used", "count": 3}]'::jsonb),
  ('Bandage - MC (10)', '[{"label": "Used", "count": 19}]'::jsonb),
  ('Bastard Axe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Axe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Axe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Axe - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Hammer - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Hammer - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Hammer - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Mace - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Mace - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Mace - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Spear - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Spear - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Spear - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Sword - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Bastard Sword - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bastard Sword - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Battle Axe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Battle Axe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Battle Axe - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Berserk (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blade Oil (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blow Darts (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blow Darts (10) - Kereste', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blow Darts (10) - MC', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blow Darts (10) - MC Kereste', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Blowpipe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Blowpipe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Blowpipe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Blowpipe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bow - Kereste and Arrows', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bow - MC Kereste and Arrows', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bow - MC and Arrows', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Bow and Arrows', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Buckler - Adamantine', '[{"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Buckler - MC', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Buckler - MC Adamantine', '[{"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Buckler - MC Kereste', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Buckler - MC Mithril', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Buckler - MC Silver', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Candle (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Chain Links (10)', '[{"label": "Used", "count": 9}]'::jsonb),
  ('Charm - Potion - A', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('Charm - Potion - H', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('Cloth (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Club - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Club - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Club - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Container (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Cord (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Creeping Death (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Cure All (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Dagger', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Dagger - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Dagger - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Dagger - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Disease (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Divine Blessing - Oil - A', '[{"label": "Deity", "count": 0}]'::jsonb),
  ('Divine Blessing - Oil - H', '[{"label": "Deity", "count": 0}]'::jsonb),
  ('Dragon Breath (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Energy Boost (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Euphoric (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('False Death (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Fate - Potion - A', '[{"label": "Fate provided to caster (name)", "count": 0}]'::jsonb),
  ('Fate - Potion - H', '[{"label": "Fate provided to caster (name)", "count": 0}]'::jsonb),
  ('Fighting Glove', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Fighting Glove - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Fighting Glove - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Fighting Glove - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Find Things - Potion - A', '[{"label": "Item to be found", "count": 0}]'::jsonb),
  ('Find Things - Potion - H', '[{"label": "Item to be found", "count": 0}]'::jsonb),
  ('Fire Oil (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Flail', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Flail - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Flail - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flail - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Flameless Fire (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Flash Powder (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Garrote', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Garrote - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Garrote - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Garrote - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Garrote - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Garrote - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Garrote - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Garrote - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Gas Cloud (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Gold Bar', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Gold Bar (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Grease (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Greater Adrenal Rush (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Greater Charm - Potion - A', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('Greater Charm - Potion - H', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('Greater Mage Lock - Oil - A', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Greater Mage Lock - Oil - H', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Hallucinagen (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Hand Axe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Hand Axe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Hand Axe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Hand Axe - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Harden Flesh (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Hardware (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Healing Balm (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Heavy Sword - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - Adamantine - (Req ES2)', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Heavy Sword - Kereste - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - MC - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - MC Adamantine - (Req ES2)', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Heavy Sword - MC Kereste - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - MC Mithril - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - MC Silver - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - Mithril - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Heavy Sword - Silver - (Req ES2)', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Herb - (Player Selected Herbs) (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Adders Tongue (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Alkanet (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Aloe (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Ash (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Barberry (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Bastit (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Bishops Weed (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Bittermourn (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Blackroot (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Bloodmoss (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Bullrush (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Burdock (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Caffar (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Callin (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Cats Tail (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Colewort (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Coltsfoot (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Culkas (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Darnell (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Dog Weed (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Draff (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Dragon Tears (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Ebur (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Ergot (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Falsifal (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Fetherfew (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Flax (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Harfry (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Hemlock (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Henbane (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Kathkusa (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Lungwort (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Mandrake (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Nightshade (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Periwinkle (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Saffron (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Spider Venom (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Wolvesbane (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Herb - Woodrose (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Heroes Last Stand (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Hide (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Hovering Gas (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Illness (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Illumination (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Immunity (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - (Player Selected Ingredients) (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Alum (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Antimoni (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Aqua Regia (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Brimstone (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Chamomile (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Gum (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Manganes (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Melanc Base (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Mithril Dust (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Mondragora (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Napatha (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Orpiment (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Pitchblend (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - White Cinnabar (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Zinken (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Ingredient - Zinkenblend (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Intoxicant (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Iron (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Javelin', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Javelin - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Javelin - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Javelin - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Knife - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Knife - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Knife - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Lasting Ice (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Leather (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Leather Balm (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Leather Patching (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Leather Skin (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Lesser Mage Lock - Oil - A', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Lesser Mage Lock - Oil - H', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Lethal Poison (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Liquid Serenity (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Long Sword', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Long Sword - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Long Sword - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Long Sword - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Lumber (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Mace', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Mace - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Mace - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mace - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Mage Lock - Oil - A', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Mage Lock - Oil - H', '[{"label": "Designated Key", "count": 0}]'::jsonb),
  ('Magical Absorbant (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Magical Litmus (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Mana Water (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Mass Teleport - Potion - A', '[{"label": "Designated Location", "count": 0}]'::jsonb),
  ('Mass Teleport - Potion - H', '[{"label": "Designated Location", "count": 0}]'::jsonb),
  ('Metal Patching (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Metal Polish (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Minor Illness (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Miracle Tonic (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Mysterious Goo (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Neutralizing Paste (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Paralyze (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Parchment (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Polearm', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Polearm - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Polearm - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Polearm - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Punch Shield - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Punch Shield - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Punch Shield - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Quill and Ink (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Rope (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('SacrifIce - Potion - A', '[{"label": "Sacrificed to caster (name)", "count": 0}]'::jsonb),
  ('SacrifIce - Potion - H', '[{"label": "Sacrificed to caster (name)", "count": 0}]'::jsonb),
  ('Scabbard - Combat', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Scabbard - MC Combat', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Shield - Adamantine', '[{"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Shield - MC', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Shield - MC Adamantine', '[{"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Shield - MC Kereste', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Shield - MC Mithril', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Shield - MC Silver', '[{"label": "Resist Shatter Used", "count": 1}]'::jsonb),
  ('Short Sword', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Short Sword - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Short Sword - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Short Sword - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Silk Bag (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Silver Bar', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Silver Bar (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Sleep (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Sling', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Sling - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Slow Death (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Spark (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Spectacular Reflection (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Spellbook (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Staff - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - MC Steel', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Staff - Steel', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Sticky Foot (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Stone (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Teleport - Potion - A', '[{"label": "Designated Location", "count": 0}]'::jsonb),
  ('Teleport - Potion - H', '[{"label": "Designated Location", "count": 0}]'::jsonb),
  ('Thermal Gel (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Throwing Axe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Throwing Axe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Throwing Axe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Axe - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Throwing Dagger - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Throwing Dagger - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Throwing Dagger - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Thunderstone (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Timber Oil (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Tonfa', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Tonfa - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Tonfa - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Tonfa - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Tongue Bind (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Toxin (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('True Charm - Potion - A', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('True Charm - Potion - H', '[{"label": "Charmed to caster (name)", "count": 0}]'::jsonb),
  ('True metal (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Two Handed Axe', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Axe - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Axe - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Axe - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Hammer - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Hammer - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Hammer - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Mace - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Mace - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Mace - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Sword - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('Two Handed Sword - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Two Handed Sword - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('War Hammer - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('War Hammer - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Hammer - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('War Trident - Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - MC', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - MC Adamantine', '[{"label": "Shattered", "count": 1}, {"label": "Resist Corrode Used", "count": 1}]'::jsonb),
  ('War Trident - MC Kereste', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - MC Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - MC Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - Mithril', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('War Trident - Silver', '[{"label": "Shattered", "count": 1}]'::jsonb),
  ('Wither Limb - Potion - A', '[{"label": "Designated Limb", "count": 0}]'::jsonb),
  ('Wither Limb - Potion - H', '[{"label": "Designated Limb", "count": 0}]'::jsonb),
  ('Wonder Tonic (10) - Mixture', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Wood (10)', '[{"label": "Used", "count": 10}]'::jsonb),
  ('Wool (10)', '[{"label": "Used", "count": 10}]'::jsonb)
on conflict (lower(item_name)) do update set
  modifiers = excluded.modifiers,
  updated_at = now();
